### ISSUE TITLE
Still working ?

### ISSUE THREAD

**Issue by Triplecheeze** [kengoldfarb/pin-it-node#10]
Hi,

I think pinterest just updated,
for me pin-it-node doesn't work anymore, would like to know if this is same for all or just my code?

**Comment by carlitose** [comment]
Hi!
Pin-it-node dosen't work anymore too.
I have always "Error: Unknown error occurred while pinning"
It worked yesterday.

**Comment by kengoldfarb** [comment]
Hey @Triplecheeze @carlitose ,
Confirmed.  A recent pinterest update has broken it.

I'm going to investigate and hopefully have a fix in place soon

**Comment by kengoldfarb** [comment]
@Triplecheeze @carlitose 

I've updated and published a new version to npm: 0.2.0

Please test it out and let me know if you're still encountering issues.

**Comment by ghost** [comment]
Perfect ! Thank you ;)

**Comment by carlitose** [comment]
@kengoldfarb  Thank you!
