### ISSUE TITLE
Create Pin error

### ISSUE THREAD

**Issue by rgallagher27** [kengoldfarb/pin-it-node#11]
I'm getting errors when attempting to post to a board, has the api been changed and now breaking? 

Debug output: 

```
_getLoginPageCSRF
COOKIE 0: csrftoken=wBGrMaQ429NzDhMHjUHV6n7GrU8A9oMw; Domain=.pinterest.com; expires=Wed, 06-Apr-2016 08:19:27 GMT; Max-Age=31449600; Path=/
COOKIE 1: _pinterest_sess=TWc9PSYxelF4TW9FRzVGbTgrcG16TFd1bGtCSU90VWxhQXVMWGF6aVF3NHprcFpEcjlxR2VsUC9pL3d3M0VZbWNhdkUyZDZxdzJYMnpJeVNDM2NpVkNBWnRrRVR3UXNPdzJ5UXVYaEZIbGVKTis3NC9ucmpSblpNNUp1Z3NoK0ZuS3NKTTlBUG04SHUyTXgvV2N3MXdKQzNUeWc9PSZlY0ltcmpQRXE3NnRPZ0RjR3J5REZJZEVMZjQ9; Domain=.pinterest.com; expires=Sat, 02-Apr-2016 08:19:27 GMT; httponly; Max-Age=31103999; Path=/; secure
CSRF Token: wBGrMaQ429NzDhMHjUHV6n7GrU8A9oMw
SUCCESS: _getLoginPageCSRF
_doLogin
SUCCESS: _doLogin
_getNewCSRFForPinning
SUCCESS: _getNewCSRFForPinning
NEW CSRF:jRuvIkqZux097EDmXFoSq0eaBARB3sMX
_createPin
! ERROR: _createPin
null
400
��$U�mS]o�0
(�=�H7��   �+��W�v��)��
    Z�c5��ITܬ����H
T                      ��u���#�k�m�P����[�:����(�t���b���E.�(�V
�y����jL��ɲ.j��������θ�Qq%MH��ƕ�iŲ\�y�.�i�IW����
            ��+���wD�����19*K�Ƅ��vbݧÇ~xy�ܛ�ޖ�+��ϴ�U�c��'��ؽϫ�����^�s|����}��Tg�r��B8�G�T觶DN���P&�s�bJ�Rh�J��M�gY�E�B��b�9�t���4Os���k��;���N^��Z�u%�Fy��)<��q��*�������7rg]�L���xQ~�
                                             �4��`[�:��T���ߕ^5����3����+l�8/�ì�Pcu࠹Ҝ��f=U�Oc�}t�"���c�m�����ѳ�~�:$��+�0
                                                                                                                        ����\�z�^L�^�\࿜��Sp?�[����wq��|S:�0�*��"Ӳ�0�LC��q�O*� :��M�  {>q�Ϗߪ���a�A�C/)~?b�zHfI&���Sr#U� s%(J_��j�Ylҏ�6�
                                                                                                     *C@�/z�����/�g��
[Error: Unknown error occurred while pinning]
```

**Comment by kengoldfarb** [comment]
I just tried the [tests](https://github.com/kengoldfarb/pin-it-node/blob/0.2.0/tests/pinItTests.js) and everything seems to be working as expected.

Based on your log it looks like you were able to log in.  And then it's failing because of bad or missing parameters (status code 400) when trying to pin.

First thing I'd check is that your `boardId` is correct.  Hope that helps.

**Comment by rgallagher27** [comment]
I've used the board id returned by the createBoard() function so I can't see why that would be the problem?

**Comment by kengoldfarb** [comment]
Hmm...not sure what's going on then.  Have you tried pinning to an existing board (one that you didn't just create)?  Is the board you're pinning to a 'secret board'?

Also...can you try running the first test and see if it fails (you'll need to update username, password, and boardId): https://github.com/kengoldfarb/pin-it-node/blob/0.2.0/tests/pinItTests.js#L27

```
$ cd tests/
$ npm install
$ node_modules/.bin/mocha pinItTests.js
```

**Comment by rgallagher27** [comment]
Ah I see my problem, I've been attempting to use a YouTube link in the 'media' property for createPin.

I assume this library only works with images?

**Comment by kengoldfarb** [comment]
Yep, for now it only works with images.  Glad you got it fixed!
