### ISSUE TITLE
request not working + no error messages

### ISSUE THREAD

**Issue by eladelrom** [kengoldfarb/pin-it-node#8]
hey, can't get this API to work... It seems to be hanging with no error messages, turned on the debug mode, here's what i got;

_getLoginPageCSRF
COOKIE 0: csrftoken=W9TBKvYL10ZKAifBMmK3glWAk18dEFwM; Domain=.pinterest.com; expires=Thu, 21-Jan-2016 11:38:28 GMT; Max-Age=31449600; Path=/
COOKIE 1: _pinterest_sess=TWc9PSZCaGJFUExieE1YaHlmMHpBdEN5anRQNSt3UGJPdnc3TnZkcnErWXlFSG0rTUVJZ3BhTFM5NnZTVTF2aFhpR2orRG1vRjZvdXVDRFo2bmszYkpBMFlTZHlzWmhLK1hIekZOa1JQaVdsWXZERitPTWFRd1ErZWJtZkxyRnNmN2FRWiZOd2tscXQvTWFwYXF2UTEvWkZ2ekxudmE4SVE9; Domain=.pinterest.com; expires=Sun, 17-Jan-2016 11:38:28 GMT; httponly; Max-Age=31103999; Path=/
COOKIE remove: function (from, to) {
	var rest = this.slice((to || from) + 1 || this.length);
	this.length = from < 0 ? this.length + from : from;
	return this.push.apply(this, rest);
}

**Comment by kengoldfarb** [comment]
@eladelrom Thanks for submitting the pull request!  I'll review it soon.
